[tool.poetry]
name = "autodub"
version = "0.0.1"
description = "Dub your movies."
authors = ["Youval Vanlaer"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
moviepy = "^1.0.3"
# hmmlearn = { git = "https://github.com/hmmlearn/hmmlearn.git" }
hmmlearn = "^0.3.2"
jinja2 = "^3.1.4"
# sympy = { git = "https://github.com/sympy/sympy.git" }
sympy = "^1.14.dev0"
# pyannote-audio = { git = "https://github.com/pyannote/pyannote-audio.git", branch = "develop" }
llvmlite = "^0.43.0"
numba = "^0.60.0"
pyannote-audio = "^3.3.2"
mpmath = "^1.3.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.3"

[build-system]
requires = [
    "poetry-core>=1.1.0",
    "setuptools>=65.4.1",
    "pybind11>=2.8.0"
]
build-backend = "poetry.core.masonry.api"
